apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /path1
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}-service
                port:
                  number: {{ .Values.ingress.service_port }}
          # - path: /path2
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: {{ .Values.name }}-service
          #       port:
          #         number: {{ .Values.ingress.service_port }}
          # - path: /path3
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: {{ .Values.name }}-service
          #       port:
          #         number: {{ .Values.ingress.service_port }}
